version: '3.5'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    image: frontend:prod
    container_name: prod.front
    env_file:
      - frontend/prod.env
    environment:
      NODE_ENV: "production"
      APP: "vue-frontend"
    ports:
    - "80:80"
    depends_on:
      - server