version: '3.5'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.gen
    image: front:gen
    container_name: gen.front
    env_file:
      - frontend/gen.env
    environment:
      NODE_ENV: "development"
      APP: "vue-frontend"
    volumes:
    - "./frontend/vue-frontend/src:/vue-frontend/src"
    - "./frontend/vue-frontend/public:/vue-frontend/public"
    depends_on:
      - server
  server:
    build:
      context: server
      dockerfile: Dockerfile